namespace Crosscuting.Base.Exceptions
{
    /// <summary>
    /// Base class to raise an error generated by Dogi
    /// </summary>
    [Serializable]
    public class DogiException : ApplicationException
    {
        /// <summary>
        /// Base constructor, no information.
        /// </summary>
        public DogiException() { }

        /// <summary>
        /// Exception with informational message.
        /// </summary>
        /// <param name="message"></param>
        public DogiException(string message) : base(message) { }

        /// <summary>
        /// Exception with an informational message and the inner exception raised.
        /// </summary>
        /// <param name="message"></param>
        /// <param name="innerException"></param>
        public DogiException(string message, Exception innerException) : base(message, innerException) { }
    }
}
