namespace Crosscuting.Base.Exceptions;

/// <summary>
/// Base class to raise an error generated by authorization.
/// </summary>
[Serializable]
public class UnauthorizedException : Exception
{
    /// <summary>
    /// Base constructor, no information.
    /// </summary>
    public UnauthorizedException()
    {
    }

    /// <summary>
    /// Exception with informational message.
    /// </summary>
    /// <param name="message"></param>
    public UnauthorizedException(string? message) : base(message)
    {
    }

    /// <summary>
    /// Exception with an informational message and the inner exception raised.
    /// </summary>
    /// <param name="message"></param>
    /// <param name="innerException"></param>
    public UnauthorizedException(string? message, Exception? innerException) : base(message, innerException)
    {
    }
}