// <auto-generated />
using System;
using Infraestructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SexId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("SexId");

                    b.ToTable("Animal", "Dogi");
                });

            modelBuilder.Entity("Domain.Entities.AnimalChip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable("AnimalChip", "Dogi");
                });

            modelBuilder.Entity("Domain.Entities.IndividualProceeding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnimalChipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("ReceptionDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("AnimalChipId")
                        .IsUnique()
                        .HasFilter("[AnimalChipId] IS NOT NULL");

                    b.HasIndex("AnimalId")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.HasIndex("ReceptionDocumentId")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("IndividualProceeding", "Dogi");
                });

            modelBuilder.Entity("Domain.Entities.ReceptionDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasChip")
                        .HasColumnType("bit");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PickupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickupLocation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable("ReceptionDocument", "Dogi");
                });

            modelBuilder.Entity("Domain.Support.AnimalCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable("AnimalCategory", "Dogi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Dogs"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Cats"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Rabbits"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Rodents"
                        },
                        new
                        {
                            Id = 5,
                            Type = "Birds"
                        },
                        new
                        {
                            Id = 6,
                            Type = "Reptiles"
                        },
                        new
                        {
                            Id = 7,
                            Type = "Exotic"
                        },
                        new
                        {
                            Id = 8,
                            Type = "Farm"
                        });
                });

            modelBuilder.Entity("Domain.Support.ProceedingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable("ProceedingStatus", "Dogi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Close"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Adopted"
                        });
                });

            modelBuilder.Entity("Domain.Support.Sex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable("Sex", "Dogi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Female"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Animal", b =>
                {
                    b.HasOne("Domain.Support.Sex", "Sex")
                        .WithMany("Animals")
                        .HasForeignKey("SexId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sex");
                });

            modelBuilder.Entity("Domain.Entities.AnimalChip", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("AnimalChipId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("City");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Street");

                            b1.HasKey("AnimalChipId");

                            b1.ToTable("AnimalChip", "Dogi");

                            b1.WithOwner()
                                .HasForeignKey("AnimalChipId");
                        });

                    b.OwnsOne("Domain.ValueObjects.AnimalChipOwner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("AnimalChipId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Lastname")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("OwnerLastName");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("OwnerName");

                            b1.HasKey("AnimalChipId");

                            b1.ToTable("AnimalChip", "Dogi");

                            b1.WithOwner()
                                .HasForeignKey("AnimalChipId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.IndividualProceeding", b =>
                {
                    b.HasOne("Domain.Entities.AnimalChip", "AnimalChip")
                        .WithOne("IndividualProceeding")
                        .HasForeignKey("Domain.Entities.IndividualProceeding", "AnimalChipId");

                    b.HasOne("Domain.Entities.Animal", "Animal")
                        .WithOne("IndividualProceeding")
                        .HasForeignKey("Domain.Entities.IndividualProceeding", "AnimalId");

                    b.HasOne("Domain.Support.AnimalCategory", "AnimalCategory")
                        .WithMany("Processees")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Domain.Entities.ReceptionDocument", "ReceptionDocument")
                        .WithOne("IndividualProceeding")
                        .HasForeignKey("Domain.Entities.IndividualProceeding", "ReceptionDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Support.ProceedingStatus", "ProceedingStatus")
                        .WithMany("Processees")
                        .HasForeignKey("StatusId");

                    b.Navigation("Animal");

                    b.Navigation("AnimalCategory");

                    b.Navigation("AnimalChip");

                    b.Navigation("ProceedingStatus");

                    b.Navigation("ReceptionDocument");
                });

            modelBuilder.Entity("Domain.Entities.Animal", b =>
                {
                    b.Navigation("IndividualProceeding")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.AnimalChip", b =>
                {
                    b.Navigation("IndividualProceeding")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ReceptionDocument", b =>
                {
                    b.Navigation("IndividualProceeding");
                });

            modelBuilder.Entity("Domain.Support.AnimalCategory", b =>
                {
                    b.Navigation("Processees");
                });

            modelBuilder.Entity("Domain.Support.ProceedingStatus", b =>
                {
                    b.Navigation("Processees");
                });

            modelBuilder.Entity("Domain.Support.Sex", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
